dependencies:
 - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
 solc:
  remappings:
   - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1'
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env